baseURL = "http://example.org/" # Temporal
languageCode = "es-es"
title = "Mi Blog Educativo AWS" # O tu título
theme = "PaperMod"

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Inicio"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20